# permissions for end users to edit paths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: path-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: s3-operator
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: path-editor-role
rules:
- apiGroups:
  - s3.onyxia.sh
  resources:
  - paths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onyxia.sh
  resources:
  - paths/status
  verbs:
  - get
