apiVersion: s3.onyxia.sh/v1alpha1
kind: S3Instance
metadata:
  name: s3instance-sample
spec:
  s3Provider: minio
  url: https://minio.example.com
  secretRef: minio-credentials
  caCertSecretRef: minio-certificates
  # allowedNamespaces: "*" # if not present only resources from the same namespace is allowed
  # region: us-east-1
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  S3_ACCESS_KEY: accessKey
  S3_SECRET_KEY: secretkey
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-default-instance-cert
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
