name: Docker CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "docs/**"

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build-and-publish-docker:
    needs: lint-docker
    uses: ./.github/workflows/publish.yaml
    permissions:
      id-token: write
      contents: read
    with:
      ref: ${{ github.ref }}
      image-tag: |
        type=schedule
        type=ref,event=branch
        type=ref,event=pr
        type=ref,event=tag
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
