name: Reusable workflow to publish docker image

on:
  workflow_call:
    inputs:
      ref:
        required: false
        default: main
        type: string
      image_tag:
        required: false
        type: string
    secrets: 
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history
          ref:  ${{ github.event.inputs.source_ref }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: inseefrlab/s3-operator # list of Docker images to use as base name for tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.event.inputs.image_tag }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.build_push.outputs.digest }}
