on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to release, e.g. v1.5.13"
        required: true
        default: "v0.1.0"
      source_ref:
        description: "source ref to publish from. E.g.: main or release-x.y"
        required: true
        default: "main"
      pre_release:
        description: "Is release a pre-release ? "
        required: true
        default: false

name: Make release

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Tag branch
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git tag -f -a ${VERSION} -m "Release ${VERSION}."
          git push -f origin ${VERSION}

  release:
    name: Make release
    runs-on: ubuntu-latest
    needs:
      - tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.source_ref }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.source_ref }}
