on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to release, e.g. v1.5.13"
        required: true
        default: "v0.1.0"
      source_ref:
        description: "source ref to publish from. E.g.: main or release-x.y"
        required: true
        default: "main"
      pre_release:
        description: "Is release a pre-release ? "
        required: true
        default: false

name: Make release

jobs:
  release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.source_ref }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.source_ref }}
